{{- if .Values.certmanager.enabled -}}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: k8s-demo-issuer
  labels:
    {{- include "k8s-demo.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.certmanager.issuer.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-k8s-demo
    # Configure the challenge solvers.
    solvers:
    # An empty selector will 'match' all Certificate resources that
    # reference this Issuer.
    - http01:
        ingress:
          class: {{ .Values.certmanager.issuer.ingressClass }}
{{- end }}
